version: "3.8"

services:
  cassandra:
    image: cassandra:3.11
    ports:
    - 9042:9042
    volumes:
    - cassandra:/var/lib/cassandra
  redis:
    image: redis:6.0
    ports:
    - 6379:6379
    volumes:
      - redis:/data
  es:
    container_name: es.7.6.2
    image: elasticsearch:7.6.2
    ports:
      - 9200:9200
    volumes:
      - es:/data
    environment:
      discovery.type: single-node

volumes:
  cassandra: {}
  redis: {}
  es: {}
