###
POST http://localhost:8080/api/write/single
Content-Type: application/json

{
  "tenant": "t-1",
  "metricName": "cpu_idle",
  "tags": {
    "os": "linux",
    "host": "h-3",
    "deployment": "dev"
  },
  "ts": {{$timestamp}},
  "value": {{$randomInt}}
}

###
GET http://localhost:8080/api/metadata/metricNames?tenant=t-1

###
GET http://localhost:8080/api/metadata/tagKeys?tenant=t-1&metricName=cpu_idle

###
GET http://localhost:8080/api/metadata/tagValues?
  tenant=t-1
  &metricName=cpu_idle
  &tagKey=os

###
GET http://localhost:8080/api/query?
  tenant=t-1
  &metricName=cpu_idle
  &tag=os=linux
  &start=2020-08-23T17:53:00Z
  &end=2020-08-24T00:54:40Z
