### single
POST http://localhost:8080/api/put
Content-Type: application/json

{
  "metric": "cpu_idle",
  "tags": {
    "tenant": "t-1",
    "os": "linux",
    "host": "h-1",
    "deployment": "prod"
  },
  "timestamp": {{$timestamp}},
  "value": {{$randomInt}}
}

### multi
POST http://localhost:8080/api/put
Content-Type: application/json

[
{
  "metric": "cpu_idle",
  "tags": {
    "tenant": "t-1",
    "os": "linux",
    "host": "h-1",
    "deployment": "prod"
  },
  "timestamp": {{$timestamp}},
  "value": {{$randomInt}}
},
{
  "tenant": "t-1",
  "metric": "cpu_idle",
  "tags": {
    "tenant": "t-1",
    "os": "windows",
    "host": "h-2",
    "deployment": "prod"
  },
  "timestamp": {{$timestamp}},
  "value": {{$randomInt}}
},
{
  "metric": "cpu_idle",
  "tags": {
    "tenant": "t-1",
    "os": "linux",
    "host": "h-3",
    "deployment": "dev"
  },
  "timestamp": {{$timestamp}},
  "value": {{$randomInt}}
}
]


###
GET http://localhost:8080/api/metadata/metricNames?tenant=t-1

###
GET http://localhost:8080/api/metadata/tagKeys?tenant=t-1&metricName=cpu_idle

###
GET http://localhost:8080/api/metadata/tagValues?
  tenant=t-1
  &metricName=cpu_idle
  &tagKey=os

### raw
GET http://localhost:8080/api/query?
  tenant=t-1
  &metricName=cpu_idle
  &tag=os=linux
  &tag=deployment=prod
  &start=2020-09-15T16:00:00Z
  &end=2020-09-15T17:00:00Z

### downsampled
GET http://localhost:8080/api/query?
  tenant=t-1
  &metricName=cpu_idle
  &aggregator=min
  &granularity=PT2M
  &tag=os=linux
  &tag=deployment=prod
  &start=2020-09-15T16:00:00Z
  &end=2020-09-15T17:00:00Z
