### single
POST http://localhost:8080/api/put
Content-Type: application/json

{
  "metric": "memory_free",
  "tags": {
    "tenant": "t-1",
    "os": "linux",
    "host": "h-1",
    "deployment": "prod"
  },
  "timestamp": {{$timestamp}},
  "value": {{$randomInt}}
}

### multi
POST http://localhost:8080/api/put
Content-Type: application/json

[
{
  "metric": "memory_free",
  "tags": {
    "tenant": "t-1",
    "os": "linux",
    "host": "h-1",
    "deployment": "prod"
  },
  "timestamp": {{$timestamp}},
  "value": {{$randomInt}}
},
{
  "tenant": "t-1",
  "metric": "memory_free",
  "tags": {
    "tenant": "t-1",
    "os": "windows",
    "host": "h-2",
    "deployment": "prod"
  },
  "timestamp": {{$timestamp}},
  "value": {{$randomInt}}
},
{
  "metric": "memory_free",
  "tags": {
    "tenant": "t-1",
    "os": "linux",
    "host": "h-3",
    "deployment": "dev"
  },
  "timestamp": {{$timestamp}},
  "value": {{$randomInt}}
}
]


###
GET http://localhost:8080/api/metadata/tenants

###
GET http://localhost:8080/api/metadata/metricNames?tenant=t-1

###
GET http://localhost:8080/api/metadata/tagKeys?tenant=t-1&metricName=memory_free

###
GET http://localhost:8080/api/metadata/tagValues?
  tenant=t-1
  &metricName=memory_free
  &tagKey=resource_label

### raw
# start and end can also be ISO8601 format like 2020-10-23T16:00:00Z
# or epoch seconds
# or epoch milliseconds
# end is optional and defaults to "now"
GET http://localhost:8080/api/query?
  tenant=t-1
  &metricName=memory_free
  &tag=os=linux
  &start=3h-ago

### raw
GET http://localhost:8080/api/query?
  tenant=t-1
  &metricName=memory_free
  &tag=os=linux
  &start=1h-ago

### downsampled 5m
GET http://localhost:8080/api/query?
  tenant=t-1
  &metricName=memory_free
  &tag=os=linux
  &start=48h-ago
  &aggregator=min
  &granularity=PT5M

### downsampled 1h
GET http://localhost:8080/api/query?
  tenant=t-1
  &metricName=memory_free
  &tag=os=linux
  &start=3d-ago
  &aggregator=min
  &granularity=PT1H

### downsampled
GET http://localhost:8080/api/query?
  tenant=t-1
  &metricName=memory_free
  &tag=os=linux
  &start=1h-ago
  &aggregator=min
  &granularity=pt2m
