apiVersion: v1
kind: Service
metadata:
  name: ceres
spec:
  selector:
    app: ceres
  ports:
    - port: 8080
      name: http
    # only for dev testing:
    - port: 8081
      name: actuator
    # only for dev testing:
    - port: 7091
      name: jmx
