---
name: Dev promotion

on: 
#  push:
#    branches: 
#      - master
#    paths-ignore:
#      - '.github/workflows/**'
#      - 'test-script'
#      - '**/pom.xml' 
  workflow_dispatch:

env:
  IMAGE_NAME: ceres
  HELM_CHART: ceres
  HELM_CHART_FOLDER: helm-ceres/cherts/ceres
  CLUSTER_NAME: primary-cluster

jobs:
  Setup:
    uses: ./.github/workflows/getVersion.yml
    with:
      image: ceres
    secrets:
      account:  ${{ secrets.GCP_DEV_ACC }}
      GCPCreds: ${{ secrets.GCP_SA_JSON }} 

  Build:
    needs: Setup

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/GCPSetup
        with:
          GCPCreds: ${{ secrets.GCP_SA_JSON }} 

      - name: 'Maven settings'
        run: 'gsutil cp gs://salus-mavenrepository/m2-settings.xml ./.mvn/settings.xml'

      - name: Docker login
        run: gcloud auth configure-docker gcr.io -q

      - name: .m2 forder [*** fix it please ***]
        run: sed -i '/<localRepository>/d' ./.mvn/settings.xml

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '14'
          distribution: 'adopt-hotspot'
          cache: maven

      ### Maven build
      - name: Build with Maven
        shell: bash
        run: |
          ARTIFACT_VERSION=${{ needs.Setup.outputs.new_version }}-SNAPSHOT
          mvn build-helper:parse-version versions:set -DnewVersion=$ARTIFACT_VERSION versions:commit
          mvn -B -U -s .mvn/settings.xml deploy jib:build -Ddocker.image.prefix=gcr.io/${{ secrets.GCP_DEV_ACC }} 

  Deploy:
    runs-on: ubuntu-latest
    needs: [Build]

    steps:
      - uses: actions/checkout@v3
      
      - uses: ./.github/actions/GCPSetup
        with:
          GCPCreds: ${{ secrets.GCP_SA_JSON }} 
          k8sSetup: "TRUE"
          GCPaccount: ${{ secrets.GCP_DEV_ACC }}
          clusterName: $CLUSTER_NAME

      - name: Checkout helm-repo
        uses: actions/checkout@v3
        with:
          repository: rax-maas/helm-ceres
          ref: master
          path: helm-ceres
          token: ${{ secrets.GIT_TOKEN }}

      - uses: azure/setup-helm@v3
        with:
          version: 3.9.0
        id: install
      
      ### deploying
      - name: Getting latest digest
        shell: bash
        run: | 
          DIGEST=$(gcloud container images list-tags gcr.io/${{ secrets.GCP_DEV_ACC }}/$IMAGE_NAME --filter TAGS=latest --format=json | jq .[0]."digest" | tr -d "\"" | awk -F ":" '{print $2}')
          helm upgrade $HELM_CHART $HELM_CHART_FOLDER --set image.repository=gcr.io/${{ secrets.GCP_DEV_ACC }}/${IMAGE_NAME}@sha256,image.tag=$DIGEST
