---
name: Tests automation Stage

on:
  workflow_run:
    workflows: ["Stage promotion"]
    types:
      - completed
  workflow_dispatch:

env:
    CLUSTER_NAME: primay-cluster
    SELECTOR: ceres
    LABEL: app.kubernetes.io/name

jobs:
  K8s:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/GCPSetup
        with:
          GCPCreds: ${{ secrets.GCP_SA_JSON }} 
          k8sSetup: "TRUE"
          clusterName: $CLUSTER_NAME
          GCPaccount: ${{ secrets.GCP_STAGE_ACC }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x' 
          architecture: 'x64' 

      - name: Pod Test
        run: python test-scripts/k8sPodStatus.py -l $SELECTOR -s $LABEL

  Smoke-test:
    runs-on: ubuntu-latest
    needs: ["Readiness"]

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/GCPSetup
        with:
          GCPCreds: ${{ secrets.GCP_SA_JSON }} 
          k8sSetup: "TRUE"
          clusterName: $CLUSTER_NAME
          GCPaccount: ${{ secrets.GCP_DEV_ACC }}

      - run: python3 ./test-scripts/runTest.py -t Smoke-test -l ./test-scripts/test-plan-dev.yml -d ./test-scripts
